name: Build and test images
on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '**'

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --prune --unshallow
          sudo apt update && sudo apt install -y jq
      - id: set-matrix
        run: |
          content=`cat .github/flavors.json  | jq 'map(select(.frameworkonly != "true"))'`
          # the following lines are only required for multi line json
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          # end of optional handling for multi line json
          echo "::set-output name=matrix::{\"include\": $content }"
  core:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    secrets: inherit
    with:
      flavor: ${{ matrix.flavor }}
    needs:
      - get-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.get-matrix.outputs.matrix)}}
  install:
    uses: ./.github/workflows/reusable-install-test.yaml
    with:
      flavor: ${{ matrix.flavor }}
      label: ${{ matrix.label }}
    needs:
      - core
    strategy:
      fail-fast: true
      matrix:
        label:
          - "install-test"
        flavor:
          - opensuse-leap
  acceptance:
    uses: ./.github/workflows/reusable-qemu-acceptance-test.yaml
    with:
      flavor: ${{ matrix.flavor }}
    needs:
      - core
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: "opensuse-leap"
  upgrade:
    uses: ./.github/workflows/reusable-upgrade-with-cli-test.yaml
    with:
      flavor: ${{ matrix.flavor }}

    needs:
      - core
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: opensuse-leap
  upgrade-latest:
    uses: ./.github/workflows/reusable-upgrade-latest-test.yaml
    with:
      flavor: ${{ matrix.flavor }}
    needs:
    - core
    strategy:
      fail-fast: false
      matrix:
        include:
          # - flavor: alpine # enable once we have 1 alpine pure release, otherwise it cant find the latest released version for that flavor
          - flavor: opensuse-leap
          # - flavor: "ubuntu"
          # - flavor: "ubuntu"
          # - flavor: "ubuntu"
  encryption:
    uses: ./.github/workflows/reusable-encryption-test.yaml
    with:
      flavor: ${{ matrix.flavor }}
      label: ${{ matrix.label }}
    needs:
      - core
    strategy:
      fail-fast: true
      matrix:
        label:
          - "local-encryption"
          - "remote-auto"
          - "remote-static"
        flavor:
          - "opensuse-leap"
  standard:
    uses: ./.github/workflows/reusable-build-provider.yaml
    with:
      flavor: ${{ matrix.flavor }}
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - "opensuse-leap"
  various:
    uses: ./.github/workflows/reusable-provider-tests.yaml
    with:
      flavor: ${{ matrix.flavor }}
      label: ${{ matrix.label }}
    needs:
      - standard
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        label:
          - "provider-upgrade"
          - "provider-decentralized-k8s"
          - "provider-upgrade-k8s"
        flavor:
          - "opensuse-leap"
  standard-upgrade-latest:
    uses: ./.github/workflows/reusable-provider-upgrade-latest-test.yaml
    with:
      flavor: ${{ matrix.flavor }}
    needs:
      - standard
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        flavor:
          - "opensuse-leap"