name: Build and test PRs
on:
  pull_request:
    paths:
      - '**'

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
jobs:
  core:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: ubuntu

  core-opensuse-tumbleweed:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: opensuse-tumbleweed

  core-alpine-ubuntu:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: alpine-ubuntu

  core-almalinux:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: almalinux

  core-fedora:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: fedora

  core-ubuntu-20-lts:
    uses: ./.github/workflows/reusable-build-flavor.yaml
    with:
      flavor: ubuntu-20-lts

  install:
    uses: ./.github/workflows/reusable-install-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  zfs:
    uses: ./.github/workflows/reusable-zfs-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  acceptance:
    uses: ./.github/workflows/reusable-qemu-acceptance-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  bundles:
    uses: ./.github/workflows/reusable-qemu-bundles-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  reset:
    uses: ./.github/workflows/reusable-qemu-reset-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  netboot:
    uses: ./.github/workflows/reusable-qemu-netboot-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  upgrade:
    uses: ./.github/workflows/reusable-upgrade-with-cli-test.yaml
    with:
      flavor: ubuntu
    needs:
      - core

  upgrade-latest:
    uses: ./.github/workflows/reusable-upgrade-latest-test.yaml
    with:
      flavor: ubuntu
    needs:
    - core

  encryption:
    uses: ./.github/workflows/reusable-encryption-test.yaml
    with:
      flavor: ubuntu
      label: ${{ matrix.label }}
    needs:
      - core
    strategy:
      fail-fast: true
      matrix:
        label:
          - "local-encryption"
          - "remote-auto"
          - "remote-static"
          - "remote-https-pinned"
          - "remote-https-bad-cert"
