name: Reusable workflow - zfs test

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string

jobs:
  test:
    runs-on: kvm
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: kairos-${{ inputs.flavor }}.iso.zip
          path: ./build
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./build
      - name: Install earthly
        uses: jimmykarily/luet-install-action@v1.2
        with:
          repository: quay.io/kairos/packages
          packages: utils/earthly
      - name: Block all traffic to metadata ip  # For cloud runners, the metadata ip can interact with our test machines
        run: |
          sudo iptables -I INPUT -s 169.254.169.254 -j DROP
          sudo iptables -I OUTPUT -d 169.254.169.254 -j DROP
      - run: |
          export ISO=$(ls $PWD/kairos-*${{ inputs.flavor }}*).iso
          earthly +run-qemu-test --TEST_SUITE=zfs --FLAVOR=${{ inputs.flavor }}
