name: Reusable workflow - zfs test

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string

jobs:
  test:
    runs-on: kvm
    steps:
      - uses: actions/checkout@v4
      - name: Download ISO
        id: iso
        uses: actions/download-artifact@v3
        with:
          name: kairos-${{ inputs.flavor }}.iso.zip
      - name: Display structure of downloaded files
        run: ls -R
      - name: Install earthly
        uses: jimmykarily/luet-install-action@v1.2
        with:
          repository: quay.io/kairos/packages
          packages: utils/earthly
      - run: |
          earthly +run-qemu-test --PREBUILT_ISO=$(ls kairos-core-*${{ inputs.flavor }}*.iso) --TEST_SUITE=zfs --FLAVOR=${{ inputs.flavor }}
