name: WebUI tests
on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!docs/**'
  pull_request:
    paths:
      - '**'
      - '!docs/**'

concurrency:
  group: ci-webui-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  webui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install earthly
        uses: Luet-lab/luet-install-action@v1
        with:
          repository: quay.io/kairos/packages
          packages: utils/earthly
      - name: WebUI tests
        run: earthly +webui-tests
